name: Torrent 

on:
  workflow_dispatch:
    inputs:
      torrent:
        description: Torrent Link
        required: true
jobs:
  tor:
    runs-on: ubuntu-latest
    steps:
    - name: Start Torrent
      run: aria2c "${{ github.event.inputs.torrent}}
